
import java.awt.Color;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Shubham Singh
 */
public class window2 extends javax.swing.JFrame {
      String symbol;
      int k; 
     String save;
     int p1;
     int p2;
      String play1;
      String play2;
     int c;
    /**
     * Creates new form window2
     */
    public window2() {
        
        initComponents();
        symbol=window1.symbol;
        save=symbol;
        k=0;
        play1=window1.play1;
        play2=window1.play2;
        p1=p2=0;
        c=0;
        j11.setBackground(Color.BLACK);
        j11.setForeground(Color.WHITE);
         j12.setBackground(Color.BLACK);
        j12.setForeground(Color.WHITE);
         j13.setBackground(Color.BLACK);
        j13.setForeground(Color.WHITE);
        
         j14.setBackground(Color.BLACK);
        j14.setForeground(Color.WHITE);
         j15.setBackground(Color.BLACK);
        j15.setForeground(Color.WHITE);
         j16.setBackground(Color.BLACK);
        j16.setForeground(Color.WHITE);
        
         j17.setBackground(Color.BLACK);
        j17.setForeground(Color.WHITE);
         j18.setBackground(Color.BLACK);
        j18.setForeground(Color.WHITE);
         j19.setBackground(Color.BLACK);
        j19.setForeground(Color.WHITE);
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jfram = new javax.swing.JFrame();
        leaderpanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tf1 = new javax.swing.JTextField();
        tf2 = new javax.swing.JTextField();
        jdisplay = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        j13 = new javax.swing.JButton();
        j11 = new javax.swing.JButton();
        j18 = new javax.swing.JButton();
        j17 = new javax.swing.JButton();
        j14 = new javax.swing.JButton();
        j15 = new javax.swing.JButton();
        j12 = new javax.swing.JButton();
        j19 = new javax.swing.JButton();
        j16 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jp1 = new javax.swing.JTextField();
        jtdisplay = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jp2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        leaderpanel.setBackground(new java.awt.Color(0, 0, 0));
        leaderpanel.setForeground(new java.awt.Color(255, 0, 0));

        jLabel6.setBackground(new java.awt.Color(102, 102, 102));
        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("  LEADERBOARD");
        jLabel6.setOpaque(true);

        jLabel7.setBackground(new java.awt.Color(177, 144, 144));
        jLabel7.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel7.setText("  WINNER");
        jLabel7.setOpaque(true);

        jLabel8.setBackground(new java.awt.Color(145, 142, 142));
        jLabel8.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel8.setText("   LOSER");
        jLabel8.setOpaque(true);

        tf1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        tf1.setForeground(new java.awt.Color(0, 153, 51));

        tf2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        tf2.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout leaderpanelLayout = new javax.swing.GroupLayout(leaderpanel);
        leaderpanel.setLayout(leaderpanelLayout);
        leaderpanelLayout.setHorizontalGroup(
            leaderpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leaderpanelLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(leaderpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(leaderpanelLayout.createSequentialGroup()
                        .addGroup(leaderpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(leaderpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );
        leaderpanelLayout.setVerticalGroup(
            leaderpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leaderpanelLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(leaderpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf1, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(leaderpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf2, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout jframLayout = new javax.swing.GroupLayout(jfram.getContentPane());
        jfram.getContentPane().setLayout(jframLayout);
        jframLayout.setHorizontalGroup(
            jframLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(leaderpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jframLayout.setVerticalGroup(
            jframLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(leaderpanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jdisplay.setBackground(new java.awt.Color(204, 204, 255));
        jdisplay.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jdisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdisplayActionPerformed(evt);
            }
        });

        j13.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        j13.setForeground(new java.awt.Color(255, 0, 51));
        j13.setText(" ");
        j13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j13ActionPerformed(evt);
            }
        });

        j11.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        j11.setForeground(new java.awt.Color(255, 0, 51));
        j11.setText(" ");
        j11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j11ActionPerformed(evt);
            }
        });

        j18.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        j18.setForeground(new java.awt.Color(255, 0, 51));
        j18.setText(" ");
        j18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j18ActionPerformed(evt);
            }
        });

        j17.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        j17.setForeground(new java.awt.Color(255, 0, 51));
        j17.setText(" ");
        j17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j17ActionPerformed(evt);
            }
        });

        j14.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        j14.setForeground(new java.awt.Color(255, 0, 51));
        j14.setText(" ");
        j14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j14ActionPerformed(evt);
            }
        });

        j15.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        j15.setForeground(new java.awt.Color(255, 0, 51));
        j15.setText(" ");
        j15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j15ActionPerformed(evt);
            }
        });

        j12.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        j12.setForeground(new java.awt.Color(255, 0, 51));
        j12.setText(" ");
        j12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j12ActionPerformed(evt);
            }
        });

        j19.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        j19.setForeground(new java.awt.Color(255, 0, 51));
        j19.setText(" ");
        j19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j19ActionPerformed(evt);
            }
        });

        j16.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        j16.setForeground(new java.awt.Color(255, 0, 51));
        j16.setText(" ");
        j16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j16ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(j11, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j14, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j17, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(j15, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j12, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j18, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(j16, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j13, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j19, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j11, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j12, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j13, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j14, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j15, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j16, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j18, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j17, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j19, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel2.setText("    PLAYER 1");
        jLabel2.setOpaque(true);

        jLabel3.setBackground(new java.awt.Color(153, 153, 153));
        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("       SCORECARD");
        jLabel3.setOpaque(true);

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel4.setText("    PLAYER 2");
        jLabel4.setOpaque(true);

        jp1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jp1.setText("   0");

        jtdisplay.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jtdisplay.setText(" ");
        jtdisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtdisplayActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(153, 153, 153));
        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel5.setText("   Tournament Winner");
        jLabel5.setOpaque(true);

        jp2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jp2.setText("   0");

        jButton1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jButton1.setText("LEADERBOARD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jp1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jp2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtdisplay)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(jp1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(jp2))
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtdisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jdisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jdisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 19, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
       
    public void docheck(){
        c++;
        if(("Player Xe wins Round "+Integer.toString(c)).equals(jdisplay.getText())){
             if(save.equals("Xe")){
                 p1++;
             }
             else p2++;
        }
        else if(("Player Ox wins Round "+Integer.toString(c)).equals(jdisplay.getText())){
             if(save.equals("Ox")){
                 p1++;
             }
             else p2++;
        }
        if(p1>=3){
            
            jtdisplay.setText(play1+" wins Tournament");
            tf1.setText(play1+" with "+p1+" win");
            tf2.setText(play2+" with "+p2+" win");
        }
        else if(p2>=3){
           
            jtdisplay.setText(play2+" wins Tournament");
            tf1.setText(play2+" with "+p2+" win");
            tf2.setText(play1+" with "+p1+" win");
        }
        else if(c==5){
            if((p1==p2)){
            jtdisplay.setText("Tournament draw");
            tf1.setText("Match Draws");
            tf2.setText("Match Draws");}
            else if(p1>p2)
            { jtdisplay.setText(play1+" wins Tournament");
            tf1.setText(play1+" with "+p1+" win");
            tf2.setText(play2+" with "+p2+" win");
            }else
            {   jtdisplay.setText(play2+" wins Tournament");
                   tf1.setText(play2+" with "+p2+" win");
            tf2.setText(play1+" with "+p1+" win");    
            }
        }
       // else return;
    } 
    
   public void changecolo(){
        j11.setBackground(Color.BLACK);
        j11.setForeground(Color.WHITE);
         j12.setBackground(Color.BLACK);
        j12.setForeground(Color.WHITE);
         j13.setBackground(Color.BLACK);
        j13.setForeground(Color.WHITE);
        
         j14.setBackground(Color.BLACK);
        j14.setForeground(Color.WHITE);
         j15.setBackground(Color.BLACK);
        j15.setForeground(Color.WHITE);
         j16.setBackground(Color.BLACK);
        j16.setForeground(Color.WHITE);
        
         j17.setBackground(Color.BLACK);
        j17.setForeground(Color.WHITE);
         j18.setBackground(Color.BLACK);
        j18.setForeground(Color.WHITE);
         j19.setBackground(Color.BLACK);
        j19.setForeground(Color.WHITE);
   }
    public void checko(){
        jp1.setText(Integer.toString(p1));
        jp2.setText(Integer.toString(p2));
        boolean winner=false; 
        if(j13.getText().equals(j11.getText())&& j12.getText().equals(j11.getText()) && j11.getText()!=" "){
             jdisplay.setText("Player "+j11.getText()+" wins Round "+(c+1));winner=true;
             changecolo();
        }
        else if(j14.getText().equals(j11.getText())&& j17.getText().equals(j11.getText()) && j11.getText()!=" "){
            jdisplay.setText("Player "+j11.getText()+" wins Round "+(c+1));winner=true;changecolo();
        }
        else if(j17.getText().equals(j18.getText())&& j17.getText().equals(j19.getText()) && j19.getText()!=" "){
            jdisplay.setText("Player "+j17.getText()+" wins Round "+(c+1));winner=true;changecolo();
        }
        else if(j13.getText().equals(j16.getText())&& j13.getText().equals(j19.getText()) && j13.getText()!=" "){
            jdisplay.setText("Player "+j19.getText()+" wins Round "+(c+1));winner=true;changecolo();
        }   
        else if(j11.getText().equals(j15.getText())&& j19.getText().equals(j11.getText()) && j11.getText()!=" "){
            jdisplay.setText("Player "+j11.getText()+" wins Round "+(c+1));winner=true;changecolo();
        }
        else if(j13.getText().equals(j15.getText())&& j17.getText().equals(j13.getText()) && j13.getText()!=" "){
            jdisplay.setText("Player "+j13.getText()+" wins Round "+(c+1));winner=true;changecolo();
        }
        else if(j12.getText().equals(j15.getText())&& j12.getText().equals(j18.getText()) && j18.getText()!=" "){
            jdisplay.setText("Player "+j18.getText()+" wins Round "+(c+1));winner=true;changecolo();
        }
        else if(j14.getText().equals(j15.getText())&& j14.getText().equals(j16.getText()) && j16.getText()!=" "){
            jdisplay.setText("Player "+j16.getText()+" wins Round "+(c+1));winner=true;changecolo();
        }
        if(winner==true){
           
            k=0;
            docheck();
            jp1.setText(Integer.toString(p1));
            jp2.setText(Integer.toString(p2));
            j11.setText(" ");j12.setText(" ");j13.setText(" ");
            j14.setText(" ");j15.setText(" ");j16.setText(" ");
            j17.setText(" ");j18.setText(" ");j19.setText(" ");
            
        }
        if(winner==false && k==8){
            jdisplay.setText("Match "+(c+1)+" draws!!!");
            changecolo();
            k=0;
            docheck();
            jp1.setText(Integer.toString(p1));
            jp2.setText(Integer.toString(p2));
            j11.setText(" ");j12.setText(" ");j13.setText(" ");
            j14.setText(" ");j15.setText(" ");j16.setText(" ");
            j17.setText(" ");j18.setText(" ");j19.setText(" ");
            
        }
    }
    
    public void j13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j13ActionPerformed
         j13.setText(symbol);
        checko();
        if(symbol.equals("Xe")){
            j13.setBackground(Color.BLUE);
        j13.setForeground(Color.WHITE); 
        symbol = "Ox";
        }
        else{
            j13.setBackground(Color.GREEN);
        j13.setForeground(Color.WHITE);
          symbol="Xe";
          
                }k++;
         
// TODO add your handling code here:
    }//GEN-LAST:event_j13ActionPerformed

    public void j11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j11ActionPerformed
        j11.setText(symbol);
         checko();
        if(symbol.equals("Xe")){
            j11.setBackground(Color.BLUE);
        j11.setForeground(Color.WHITE);
        symbol = "Ox";
        }
        else{
            j11.setBackground(Color.GREEN);
        j11.setForeground(Color.WHITE);
             symbol="Xe";
                }k++;
    }//GEN-LAST:event_j11ActionPerformed

    public void j18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j18ActionPerformed
         j18.setText(symbol);
        checko();
        if(symbol.equals("Xe")){
            j18.setBackground(Color.BLUE);
        j18.setForeground(Color.WHITE);
        symbol = "Ox";
        }
        else{
            j18.setBackground(Color.GREEN);
        j18.setForeground(Color.WHITE);
            symbol="Xe";
                }k++;//handling code here:
    }//GEN-LAST:event_j18ActionPerformed

    public void j17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j17ActionPerformed
         j17.setText(symbol);
        checko();
        if(symbol.equals("Xe")){
            j17.setBackground(Color.BLUE);
        j17.setForeground(Color.WHITE);
         symbol = "Ox";
        }
        else{
            j17.setBackground(Color.GREEN);
        j17.setForeground(Color.WHITE);
            symbol="Xe";
                }k++;
// TODO add your handling code here:
    }//GEN-LAST:event_j17ActionPerformed

    public void j14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j14ActionPerformed
         j14.setText(symbol);
        checko();
        if(symbol.equals("Xe")){
            j14.setBackground(Color.BLUE);
        j14.setForeground(Color.WHITE);
         symbol = "Ox";
        }
        else{
            j14.setBackground(Color.GREEN);
        j14.setForeground(Color.WHITE);
             symbol="Xe";
                }k++;
        // TODO add your handling code here:
    }//GEN-LAST:event_j14ActionPerformed

    public void j15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j15ActionPerformed
         j15.setText(symbol);
        checko();
        if(symbol.equals("Xe")){
            j15.setBackground(Color.BLUE);
        j15.setForeground(Color.WHITE);
         symbol = "Ox";
        }
        else{
            j15.setBackground(Color.GREEN);
        j15.setForeground(Color.WHITE);
            symbol="Xe";
                }k++;
// TODO add your handling code here:
    }//GEN-LAST:event_j15ActionPerformed

    public void j12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j12ActionPerformed
         j12.setText(symbol);
        checko();
        if(symbol.equals("Xe")){
            j12.setBackground(Color.BLUE);
        j12.setForeground(Color.WHITE);
         symbol = "Ox";
        }
        else{
            j12.setBackground(Color.GREEN);
        j12.setForeground(Color.WHITE);
            symbol="Xe";
                }k++;
// TODO add your handling code here:
    }//GEN-LAST:event_j12ActionPerformed

    public void j19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j19ActionPerformed
         j19.setText(symbol);
        checko();
        if(symbol.equals("Xe")){
            j19.setBackground(Color.BLUE);
        j19.setForeground(Color.WHITE);
         symbol = "Ox";
        }
        else{
            j19.setBackground(Color.GREEN);
        j19.setForeground(Color.WHITE);
            symbol="Xe";
                }k++;
        
// TODO add your handling code here:
    }//GEN-LAST:event_j19ActionPerformed

    public void j16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j16ActionPerformed
         j16.setText(symbol);
        checko();
        if(symbol.equals("Xe")){
            j16.setBackground(Color.BLUE);
        j16.setForeground(Color.WHITE);
         symbol = "Ox";
        }
        else{
            j16.setBackground(Color.GREEN);
        j16.setForeground(Color.WHITE);
            symbol="Xe";
                }k++;
        // TODO add your handling code here:
    }//GEN-LAST:event_j16ActionPerformed

    public void jtdisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtdisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtdisplayActionPerformed

    public void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       // new window3().setVisible(true);
    //    this.setVisible(false);
        this.setVisible(false);
        jfram.setVisible(true);
        jfram.setSize(380,272);
        jfram.setResizable(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jdisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jdisplayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
       // window2 w=new window2();
       // w.incept();
       //    window1 o=new window1();
          //symbol=o.symbol;
          
          //save=symbol;
          
          //play1=o.play1;
          //play2=o.play2;
          //System.out.print(symbol);
          
//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(window2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(window2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(window2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(window2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
         
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new window2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton j11;
    private javax.swing.JButton j12;
    private javax.swing.JButton j13;
    private javax.swing.JButton j14;
    private javax.swing.JButton j15;
    private javax.swing.JButton j16;
    private javax.swing.JButton j17;
    private javax.swing.JButton j18;
    private javax.swing.JButton j19;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jdisplay;
    private javax.swing.JFrame jfram;
    private javax.swing.JTextField jp1;
    private javax.swing.JTextField jp2;
    private javax.swing.JTextField jtdisplay;
    private javax.swing.JPanel leaderpanel;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf2;
    // End of variables declaration//GEN-END:variables
}
